FROM ubuntu:bionic
LABEL maintainer "Pascal Martineau <pascal@lewebsimple.ca>"

# Default Apache2 UID / GID
ENV APACHE2_UID 1000
ENV APACHE2_GID 1000

# Install Apache2 and useful libraries
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  apache2 \
  msmtp \
  apt-transport-https build-essential ca-certificates gnupg software-properties-common \
  curl git imagemagick less iputils-ping nano openssh-client rsync wget \
  language-pack-fr-base tzdata \
  ffmpeg \
  && rm -rf /var/lib/apt/lists/*

# Install PHP
RUN add-apt-repository ppa:ondrej/php \
  && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  php5.6 php5.6-cli php5.6-curl php5.6-dev php5.6-gd php5.6-intl php5.6-mbstring php5.6-mysql php-pear php5.6-xdebug php5.6-xml php5.6-zip \
  && rm -rf /var/lib/apt/lists/*

# Install Node.js 14.x
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
  && apt-get install -y nodejs \
  && rm -rf /var/lib/apt/lists/*

# Copy configuration files
COPY config/ /

# Configure Apache2 / PHP
RUN set -ex \
  # Load Apache2 environment variables
  && . /etc/apache2/envvars \
  # Enable Apache2 configurations
  && a2enconf fqdn conf-extra \
  # Enable Apache2 modules
  && a2enmod expires headers remoteip rewrite vhost_alias \
  # Enable Apache2 vhosts
  && a2ensite vhosts \
  && apache2ctl graceful \
  # Remove SSL vhostn
  && rm /etc/apache2/sites-available/default-ssl.conf \
  # Disable Indexes everywhere
  && sed -e '/Options Indexes FollowSymLinks/ s/^#*/#/' -i /etc/apache2/apache2.conf \
  # Output error log to stderr
  && ln -sfT /dev/stderr "${APACHE_LOG_DIR}/error.log" \
  && ln -sfT /dev/stdout "${APACHE_LOG_DIR}/access.log" \
  # Install Xdebug with pecl
  && pecl install xdebug-2.9.8 \
  # Create Xdebug directory
  && mkdir -p /tmp/xdebug \
  # Change UID/GID of www-data to match local user
  && usermod --non-unique --uid ${APACHE2_UID} www-data \
  && groupmod --non-unique --gid ${APACHE2_GID} www-data \
  # Adjust directory permissions
  && chown -R www-data:www-data /var/www /tmp \
  # Reload Apache2
  # Generate fr_CA locale
  && locale-gen fr_CA.utf8

# Install NPM packages
RUN npm i -g \
  mammoth \
  yarn

VOLUME ["/etc/apache2/conf-extra","/var/www/html","/tmp"]
WORKDIR /var/www/html

EXPOSE 80

CMD ["/docker-entrypoint.sh"]
