version: '3.7'

services:

  # Apache2
  apache2:
    build: .
    container_name: apache2
    restart: always
    environment:
      - APACHE2_TLD=${TLD-local}
      - APACHE2_ENABLE_XDEBUG=${APACHE2_ENABLE_XDEBUG-yes}
      - APACHE2_MSMTP_HOST=${APACHE2_MSMTP_HOST}
      - APACHE2_MSMTP_FROM=${APACHE2_MSMTP_FROM}
      - TZ=${TZ-America/Toronto}
      - HTTPS_METHOD=noredirect
      - VIRTUAL_HOST=*.${TLD-local},${LETSENCRYPT_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    extra_hosts:
      - "nextcloud.ledevsimple.ca:192.168.1.150"
    volumes:
      - ${DATA-./data}/apache2/conf-extra:/etc/apache2/conf-extra
      - ${DATA-./data}/apache2/tmp:/tmp
      - ${WWW-./www}/html:/var/www/html

networks:

  default:
    external: true
    name: proxy
